/**
 * Find Someone — Comprehensive Demo Investigation Dataset
 * Realistic evidence-backed OSINT intelligence scenarios.
 */

import type {
  Investigation,
  PersonEntity,
  OrganizationEntity,
  Source,
  Claim,
  Evidence,
  Conflict,
  TimelineEvent,
  Relationship,
  IdentityMatch,
  WorkerProgress,
} from "@/lib/find-someone/types";

export const DEMO_INVESTIGATION: Investigation = {
  id: "inv_rahul_kumar_2026",
  query: {
    raw: "Rahul Kumar Odisha",
    entityType: "person",
    name: "Rahul Kumar",
    location: "Odisha",
    sources: ["web", "profiles", "news", "documents", "india", "github"],
    filters: {
      country: "India",
      state: "Odisha",
      sourceConfidence: 80,
      identityConfidence: 85,
    },
  },
  status: "completed",
  mode: "standard",
  createdAt: "2026-09-12T10:15:30Z",
  completedAt: "2026-09-12T10:15:42Z",

  progress: [
    {
      type: "web",
      label: "Public Web Surface",
      status: "completed",
      progress: 100,
      resultsCount: 42,
      startedAt: "10:15:30",
      completedAt: "10:15:32",
    },
    {
      type: "profiles",
      label: "Public Profile Discovery (Sherlock/Maigret)",
      status: "completed",
      progress: 100,
      resultsCount: 14,
      startedAt: "10:15:32",
      completedAt: "10:15:34",
    },
    {
      type: "news",
      label: "Public News & Media (GDELT / RSS)",
      status: "completed",
      progress: 100,
      resultsCount: 19,
      startedAt: "10:15:33",
      completedAt: "10:15:36",
    },
    {
      type: "documents",
      label: "Document Intelligence (PDF / Research)",
      status: "completed",
      progress: 100,
      resultsCount: 8,
      startedAt: "10:15:35",
      completedAt: "10:15:38",
    },
    {
      type: "india",
      label: "Indian Public Data (data.gov.in / MCA)",
      status: "completed",
      progress: 100,
      resultsCount: 6,
      startedAt: "10:15:36",
      completedAt: "10:15:39",
    },
    {
      type: "language",
      label: "Indic Language Pipeline (IndicLID / Translit)",
      status: "completed",
      progress: 100,
      resultsCount: 5,
      startedAt: "10:15:38",
      completedAt: "10:15:40",
    },
    {
      type: "entities",
      label: "Entity Resolution & Scoring",
      status: "completed",
      progress: 100,
      resultsCount: 12,
      startedAt: "10:15:39",
      completedAt: "10:15:41",
    },
    {
      type: "graph",
      label: "Knowledge Graph Synthesis",
      status: "completed",
      progress: 100,
      resultsCount: 28,
      startedAt: "10:15:40",
      completedAt: "10:15:42",
    },
  ],

  persons: [
    {
      id: "ent_person_rahul_primary",
      type: "person",
      name: "Rahul Kumar",
      aliases: ["rahul_sec", "Rahul K.", "राहुल कुमार", "ରାହୁଲ କୁମାର"],
      metadata: {
        designation: "Principal Cybersecurity Architect & Systems Builder",
        almaMater: "National Institute of Technology Rourkela (NIT Rourkela)",
        origin: "Bhubaneswar, Odisha, India",
        currentBase: "Bengaluru / Bhubaneswar",
        specialization: "Memory Forensics, Autonomous Agent Defense, Zero Trust",
      },
      sources: [
        "src_mca_gov",
        "src_github_profile",
        "src_ieee_paper",
        "src_tech_news_2024",
        "src_linkedin_public",
      ],
      confidence: 94,
      status: "high_confidence",
      createdAt: "2026-09-12T10:15:39Z",
      updatedAt: "2026-09-12T10:15:42Z",
      profileImage:
        "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80&fm=webp",
      websites: ["https://rahulkumar-security.dev", "https://dezo.in/research"],
      locations: ["Bhubaneswar, Odisha", "Bengaluru, Karnataka"],
      organizations: ["ent_org_dezo", "ent_org_nitrkl", "ent_org_cert_in_affil"],
      publicFootprint: {
        profiles: 8,
        organizations: 3,
        websites: 2,
        publications: 7,
        documents: 5,
        newsMentions: 16,
      },
      publicProfiles: [
        {
          platform: "GitHub",
          username: "rahul-k-sec",
          url: "https://github.com/rahul-k-sec",
          confidence: 98,
          verified: true,
          lastChecked: "2026-09-12",
          metadata: { repos: "34", followers: "1,420", primaryLanguage: "Rust / Python" },
        },
        {
          platform: "LinkedIn (Public Profile)",
          username: "rahulkumar-cyber",
          url: "https://linkedin.com/in/rahulkumar-cyber",
          confidence: 94,
          verified: true,
          lastChecked: "2026-09-12",
          metadata: {
            connections: "500+",
            headline: "Chief Architect at Dezo Systems | NIT Rourkela",
          },
        },
        {
          platform: "ORCID / Scholar",
          username: "0000-0002-8192-304X",
          url: "https://orcid.org/0000-0002-8192-304X",
          confidence: 96,
          verified: true,
          lastChecked: "2026-09-11",
          metadata: { hIndex: "6", citations: "312", focus: "Firmware Forensics & Cryptography" },
        },
        {
          platform: "X / Twitter",
          username: "@rahul_infosec",
          url: "https://x.com/rahul_infosec",
          confidence: 88,
          verified: false,
          lastChecked: "2026-09-12",
          metadata: { joined: "2019", bio: "Hardware security, Indic AI, systems engineering" },
        },
        {
          platform: "Keybase",
          username: "rahulk_in",
          url: "https://keybase.io/rahulk_in",
          confidence: 92,
          verified: true,
          lastChecked: "2026-09-10",
          metadata: { pgpFingerprint: "8F3A 2910 C92B 4102 ... 19FA" },
        },
      ],
    },
    {
      id: "ent_person_rahul_candidate_2",
      type: "person",
      name: "Rahul Kumar (Delhi)",
      aliases: ["rahul_k_ai", "Dr. Rahul Kumar"],
      metadata: {
        designation: "Assistant Professor in Computational Linguistics",
        almaMater: "Jawaharlal Nehru University (JNU), New Delhi",
        origin: "New Delhi, India",
        specialization: "Indic NLP, Machine Translation",
      },
      sources: ["src_univ_delhi", "src_arxiv_nlp"],
      confidence: 64,
      status: "possible",
      createdAt: "2026-09-12T10:15:40Z",
      updatedAt: "2026-09-12T10:15:42Z",
      websites: ["https://jnu.ac.in/faculty/rkumar"],
      locations: ["New Delhi, India"],
      organizations: ["ent_org_jnu"],
      publicFootprint: {
        profiles: 3,
        organizations: 1,
        websites: 1,
        publications: 14,
        documents: 9,
        newsMentions: 4,
      },
      publicProfiles: [
        {
          platform: "Google Scholar",
          username: "rahul-kumar-nlp",
          url: "https://scholar.google.com/citations?user=nlp_rk",
          confidence: 92,
          verified: true,
          lastChecked: "2026-09-08",
          metadata: { citations: "1,140", focus: "Indic Transliteration" },
        },
        {
          platform: "GitHub",
          username: "rkumar-nlp",
          url: "https://github.com/rkumar-nlp",
          confidence: 76,
          verified: false,
          lastChecked: "2026-09-10",
          metadata: { repos: "12", primaryLanguage: "Python" },
        },
      ],
    },
  ],

  organizations: [
    {
      id: "ent_org_dezo",
      type: "company",
      name: "Dezo Systems & Applied Intelligence Pvt Ltd",
      aliases: ["Dezo.in", "Dezo Research Labs"],
      metadata: {
        incorporationNumber: "U72900OR2021PTC037182",
        status: "Active / Registered",
        registeredState: "Odisha, India",
        industry: "Enterprise AI Security & Forensic Engineering",
      },
      sources: ["src_mca_gov", "src_dezo_website"],
      confidence: 99,
      status: "confirmed",
      createdAt: "2026-09-12T10:15:39Z",
      updatedAt: "2026-09-12T10:15:42Z",
      website: "https://dezo.in",
      domain: "dezo.in",
      location: "Bhubaneswar, Odisha",
      members: ["ent_person_rahul_primary"],
    },
    {
      id: "ent_org_nitrkl",
      type: "organization",
      name: "National Institute of Technology Rourkela",
      aliases: ["NIT Rourkela", "NITR"],
      metadata: {
        category: "Institute of National Importance",
        location: "Rourkela, Sundargarh District, Odisha",
      },
      sources: ["src_nit_alumni_portal"],
      confidence: 97,
      status: "confirmed",
      createdAt: "2026-09-12T10:15:39Z",
      updatedAt: "2026-09-12T10:15:42Z",
      website: "https://nitrkl.ac.in",
      domain: "nitrkl.ac.in",
      location: "Rourkela, Odisha",
      members: ["ent_person_rahul_primary"],
    },
  ],

  entities: [],

  sources: [
    {
      id: "src_mca_gov",
      name: "Ministry of Corporate Affairs (MCA) — Registry of Companies",
      url: "https://www.mca.gov.in/mcafoportal/companyLLPMasterData.do",
      domain: "mca.gov.in",
      qualityTier: "government",
      qualityScore: 5,
      type: "government",
      retrievedAt: "2026-09-12T10:15:37Z",
      lastVerified: "2026-09-12",
      publisher: "Government of India — Ministry of Corporate Affairs",
    },
    {
      id: "src_ieee_paper",
      name: "IEEE Xplore Digital Library — Volatile Memory Triage Whitepaper",
      url: "https://ieeexplore.ieee.org/document/9842109",
      domain: "ieeexplore.ieee.org",
      qualityTier: "primary",
      qualityScore: 5,
      type: "document",
      retrievedAt: "2026-09-12T10:15:36Z",
      lastVerified: "2026-09-10",
      publisher: "IEEE Computer Society",
      author: "Rahul Kumar, et al.",
    },
    {
      id: "src_github_profile",
      name: "GitHub Developer Graph — rahul-k-sec",
      url: "https://github.com/rahul-k-sec",
      domain: "github.com",
      qualityTier: "established",
      qualityScore: 4,
      type: "profile",
      retrievedAt: "2026-09-12T10:15:33Z",
      lastVerified: "2026-09-12",
      publisher: "GitHub Public Graph API",
    },
    {
      id: "src_tech_news_2024",
      name: "Odisha Byte / Tech Herald — AI & Cyber Summit 2024",
      url: "https://odishabytes.com/tech-innovators-ai-summit-bhubaneswar-2024",
      domain: "odishabytes.com",
      qualityTier: "established",
      qualityScore: 4,
      type: "news",
      retrievedAt: "2026-09-12T10:15:35Z",
      lastVerified: "2026-09-12",
      publisher: "Odisha Bytes Editorial Bureau",
      author: "Prasanta Das, Senior Technology Correspondent",
    },
    {
      id: "src_linkedin_public",
      name: "LinkedIn Public Directory Record",
      url: "https://www.linkedin.com/in/rahulkumar-cyber",
      domain: "linkedin.com",
      qualityTier: "secondary",
      qualityScore: 3,
      type: "profile",
      retrievedAt: "2026-09-12T10:15:34Z",
      lastVerified: "2026-09-11",
      publisher: "LinkedIn Corporation",
    },
    {
      id: "src_nit_alumni_portal",
      name: "NIT Rourkela Distinguished Alumni & Thesis Archive",
      url: "https://alumni.nitrkl.ac.in/records/graduates/2019-cs-042",
      domain: "nitrkl.ac.in",
      qualityTier: "primary",
      qualityScore: 5,
      type: "database",
      retrievedAt: "2026-09-12T10:15:38Z",
      lastVerified: "2026-09-08",
      publisher: "NIT Rourkela Academic Council",
    },
    {
      id: "src_startup_odisha",
      name: "Startup Odisha Recognized Ventures Catalog",
      url: "https://startupodisha.gov.in/recognized-startups/dezo-systems",
      domain: "startupodisha.gov.in",
      qualityTier: "government",
      qualityScore: 5,
      type: "government",
      retrievedAt: "2026-09-12T10:15:38Z",
      lastVerified: "2026-09-12",
      publisher: "MSME Department, Government of Odisha",
    },
  ],

  evidence: [
    {
      id: "ev_mca_director",
      sourceId: "src_mca_gov",
      extractedText:
        "Director DIN 09248102: Rahul Kumar appointed as Director of Dezo Systems and Applied Intelligence Pvt Ltd on 14/07/2021. Registered office in Bhubaneswar, Khordha, Odisha.",
      context: "Company master data disclosure public under MCA21 portal",
      extractedAt: "2026-09-12T10:15:37Z",
      confidence: 99,
    },
    {
      id: "ev_ieee_authorship",
      sourceId: "src_ieee_paper",
      extractedText:
        "Corresponding author: Rahul Kumar (Department of Computer Science & Engineering, National Institute of Technology Rourkela, Odisha, India 769008). Focus: Kernel Memory Dump Parsing in Multi-tenant Cloud Workloads.",
      context: "Peer-reviewed conference proceedings IEEE CloudCom",
      extractedAt: "2026-09-12T10:15:36Z",
      confidence: 98,
    },
    {
      id: "ev_github_commits",
      sourceId: "src_github_profile",
      extractedText:
        "User rahul-k-sec: Public bio 'Building forensic automation and agent security at @dezo-systems. Bhubaneswar / BLR. Alum @nitrkl'. Commits to repositories: memory-triage-rs, indic-guard-nlp, zerotrust-mesh.",
      context: "Public developer profile overview and activity stream",
      extractedAt: "2026-09-12T10:15:33Z",
      confidence: 95,
    },
    {
      id: "ev_news_speaker",
      sourceId: "src_tech_news_2024",
      extractedText:
        "'Keynote speaker Rahul Kumar, co-founder of Bhubaneswar-based deep-tech startup Dezo Systems, highlighted the necessity of sovereign cyber defense and Indian language threat classification at the Odisha AI Conclave 2024.'",
      context: "Published reportage covering Eastern India Cyber Security Summit",
      extractedAt: "2026-09-12T10:15:35Z",
      confidence: 92,
    },
    {
      id: "ev_startup_grant",
      sourceId: "src_startup_odisha",
      extractedText:
        "Registration Certificate No. OD-MSME-2022-8192 issued to Dezo Systems Pvt Ltd. Key founders: Rahul Kumar, Tarik Islam. Recognized under Cyber & Deep-Tech Sector.",
      context: "State government industrial portal registry",
      extractedAt: "2026-09-12T10:15:38Z",
      confidence: 99,
    },
  ],

  claims: [
    {
      id: "cl_founded_dezo",
      subject: "Rahul Kumar",
      predicate: "founded",
      object: "Dezo Systems",
      confidence: 99,
      status: "confirmed",
      sourceId: "src_mca_gov",
      evidenceId: "ev_mca_director",
      extractedAt: "2026-09-12T10:15:37Z",
      evidenceText:
        "Appointed as Director and Founding Shareholder on 14/07/2021 (DIN 09248102, MCA21).",
    },
    {
      id: "cl_alumni_nit",
      subject: "Rahul Kumar",
      predicate: "graduated_from",
      object: "NIT Rourkela",
      confidence: 98,
      status: "confirmed",
      sourceId: "src_ieee_paper",
      evidenceId: "ev_ieee_authorship",
      extractedAt: "2026-09-12T10:15:36Z",
      evidenceText:
        "Published research with NIT Rourkela affiliation, verified through thesis archive.",
    },
    {
      id: "cl_location_odisha",
      subject: "Rahul Kumar",
      predicate: "located_in",
      object: "Bhubaneswar, Odisha",
      confidence: 94,
      status: "high_confidence",
      sourceId: "src_tech_news_2024",
      evidenceId: "ev_news_speaker",
      extractedAt: "2026-09-12T10:15:35Z",
      evidenceText: "Keynote speaker at Odisha AI Conclave, recognized by Startup Odisha MSME.",
    },
    {
      id: "cl_conflicting_joining_date_a",
      subject: "Rahul Kumar",
      predicate: "joined_org_date",
      object: "Dezo Systems (2020 pre-incorporation)",
      confidence: 72,
      status: "conflicting",
      sourceId: "src_linkedin_public",
      evidenceId: "ev_github_commits",
      extractedAt: "2026-09-12T10:15:34Z",
      evidenceText: "Public LinkedIn profile states 'Co-Founder since August 2020'.",
    },
    {
      id: "cl_conflicting_joining_date_b",
      subject: "Rahul Kumar",
      predicate: "joined_org_date",
      object: "Dezo Systems (Official MCA 2021)",
      confidence: 99,
      status: "confirmed",
      sourceId: "src_mca_gov",
      evidenceId: "ev_mca_director",
      extractedAt: "2026-09-12T10:15:37Z",
      evidenceText: "Official statutory incorporation date recorded as July 14, 2021.",
    },
  ],

  conflicts: [
    {
      id: "conf_joining_date",
      field: "Company Association Date (Dezo Systems)",
      description:
        "LinkedIn claim states August 2020 (likely R&D phase prior to legal registration), while statutory MCA filing registers official incorporation as July 14, 2021. Both sources are displayed honestly without silent merging.",
      claimA: {
        id: "cl_conflicting_joining_date_a",
        subject: "Rahul Kumar",
        predicate: "claimed_start",
        object: "August 2020",
        confidence: 72,
        status: "conflicting",
        sourceId: "src_linkedin_public",
        evidenceId: "ev_github_commits",
        extractedAt: "2026-09-12T10:15:34Z",
        evidenceText:
          "Self-published claim on LinkedIn: 'Co-Founder & Architect, Aug 2020 – Present'.",
      },
      claimB: {
        id: "cl_conflicting_joining_date_b",
        subject: "Rahul Kumar",
        predicate: "statutory_incorporation",
        object: "July 14, 2021",
        confidence: 99,
        status: "confirmed",
        sourceId: "src_mca_gov",
        evidenceId: "ev_mca_director",
        extractedAt: "2026-09-12T10:15:37Z",
        evidenceText: "Statutory MCA Incorporation Certificate U72900OR2021PTC037182.",
      },
    },
  ],

  timeline: [
    {
      id: "tl_2018_thesis",
      date: "2018-05-20",
      title: "Undergraduate Research Defense — NIT Rourkela",
      description:
        "Defended research paper on kernel-level buffer anomaly detection at Department of Computer Science, NIT Rourkela.",
      sourceId: "src_nit_alumni_portal",
      evidenceId: "ev_ieee_authorship",
      entityIds: ["ent_person_rahul_primary", "ent_org_nitrkl"],
      type: "publication",
      confidence: 98,
    },
    {
      id: "tl_2019_ieee",
      date: "2019-11-14",
      title: "IEEE Publication on Cloud Volatile Memory Triage",
      description:
        "Co-authored peer-reviewed research indexed on IEEE Xplore with 45 subsequent international citations.",
      sourceId: "src_ieee_paper",
      evidenceId: "ev_ieee_authorship",
      entityIds: ["ent_person_rahul_primary"],
      type: "publication",
      confidence: 99,
    },
    {
      id: "tl_2020_github_init",
      date: "2020-08-02",
      title: "Open-Source Release of Memory Triage Engine",
      description:
        "Published memory-triage-rs repository on GitHub, adopted by digital forensics students across India.",
      sourceId: "src_github_profile",
      evidenceId: "ev_github_commits",
      entityIds: ["ent_person_rahul_primary"],
      type: "event",
      confidence: 95,
    },
    {
      id: "tl_2021_incorporation",
      date: "2021-07-14",
      title: "Incorporation of Dezo Systems Pvt Ltd",
      description:
        "Appointed as Director and Architect of Dezo Systems under Ministry of Corporate Affairs, Bhubaneswar registry.",
      sourceId: "src_mca_gov",
      evidenceId: "ev_mca_director",
      entityIds: ["ent_person_rahul_primary", "ent_org_dezo"],
      type: "founding",
      confidence: 99,
    },
    {
      id: "tl_2022_startup_recognition",
      date: "2022-09-18",
      title: "Startup Odisha MSME Deep-Tech Grant Recognition",
      description:
        "Dezo Systems officially recognized by Government of Odisha as an emerging cyber-defense venture.",
      sourceId: "src_startup_odisha",
      evidenceId: "ev_startup_grant",
      entityIds: ["ent_org_dezo"],
      type: "affiliation",
      confidence: 99,
    },
    {
      id: "tl_2024_keynote",
      date: "2024-03-22",
      title: "Keynote Address: Eastern India Cyber & AI Conclave",
      description:
        "Delivered keynote on 'Autonomous Agents, Sovereign Infrastructure and Forensics' in Bhubaneswar.",
      sourceId: "src_tech_news_2024",
      evidenceId: "ev_news_speaker",
      entityIds: ["ent_person_rahul_primary"],
      type: "mention",
      confidence: 93,
    },
    {
      id: "tl_2026_agent_def",
      date: "2026-06-10",
      title: "Release of Indic Guard AI Defense Specification",
      description:
        "Published open technical specification for detecting multilingual social-engineering attacks in Indic scripts.",
      sourceId: "src_github_profile",
      evidenceId: "ev_github_commits",
      entityIds: ["ent_person_rahul_primary"],
      type: "publication",
      confidence: 96,
    },
  ],

  relationships: [
    {
      id: "rel_1",
      sourceEntityId: "ent_person_rahul_primary",
      targetEntityId: "ent_org_dezo",
      type: "founded",
      label: "Co-Founder & Director",
      confidence: 99,
      evidenceIds: ["ev_mca_director"],
    },
    {
      id: "rel_2",
      sourceEntityId: "ent_person_rahul_primary",
      targetEntityId: "ent_org_nitrkl",
      type: "affiliated_with",
      label: "B.Tech Alumnus & Researcher",
      confidence: 98,
      evidenceIds: ["ev_ieee_authorship"],
    },
    {
      id: "rel_3",
      sourceEntityId: "ent_org_dezo",
      targetEntityId: "ent_loc_bhubaneswar",
      type: "located_in",
      label: "Registered HQ",
      confidence: 99,
      evidenceIds: ["ev_mca_director"],
    },
    {
      id: "rel_4",
      sourceEntityId: "ent_person_rahul_primary",
      targetEntityId: "ent_doc_ieee_paper",
      type: "authored",
      label: "Primary Author",
      confidence: 99,
      evidenceIds: ["ev_ieee_authorship"],
    },
    {
      id: "rel_5",
      sourceEntityId: "ent_person_rahul_primary",
      targetEntityId: "ent_web_github",
      type: "linked_to",
      label: "Verified Developer Handle",
      confidence: 97,
      evidenceIds: ["ev_github_commits"],
    },
    {
      id: "rel_6",
      sourceEntityId: "ent_org_dezo",
      targetEntityId: "ent_gov_odisha",
      type: "recognized_by" as any,
      label: "State Recognized Venture",
      confidence: 99,
      evidenceIds: ["ev_startup_grant"],
    },
  ],

  identityMatches: [
    {
      entityId: "ent_person_rahul_primary",
      overallConfidence: 94,
      conclusion:
        "Extremely high probability of single coherent public identity. Corroborated across statutory company filings (MCA), peer-reviewed scientific publications (IEEE), GitHub commits, and government startup recognitions spanning 2018–2026. Stated pre-incorporation date on LinkedIn is explained by active R&D prior to legal registration.",
      signals: [
        {
          type: "name",
          description:
            "Exact name match 'Rahul Kumar' corroborated across all primary government and academic sources",
          confidence: 99,
          matching: true,
        },
        {
          type: "organization",
          description:
            "Direct linkage to 'Dezo Systems' verified via MCA DIN Director record and GitHub organization membership",
          confidence: 98,
          matching: true,
        },
        {
          type: "website",
          description:
            "Personal domain linked in GitHub profile resolves to verified research dossier",
          confidence: 96,
          matching: true,
        },
        {
          type: "publication",
          description:
            "IEEE research paper email matches public PGP key identity and GitHub commit author email",
          confidence: 95,
          matching: true,
        },
        {
          type: "biography",
          description:
            "Consistent technical bio phrasing: 'Memory Forensics, Autonomous Agent Defense, Systems Architecture'",
          confidence: 92,
          matching: true,
        },
        {
          type: "location",
          description:
            "Geographic triangle: Rourkela (education) -> Bhubaneswar (company HQ) -> Bengaluru (cloud operations)",
          confidence: 90,
          matching: true,
        },
      ],
      conflicts: [
        {
          type: "Founding Date Discrepancy",
          description:
            "LinkedIn claims August 2020 while MCA statutory certificate dates July 14, 2021. Treated as pre-incorporation R&D phase.",
          severity: "low",
        },
      ],
    },
  ],
};

export const DEMO_COMPANY: import("@/lib/find-someone/types").CompanyIntelligence = {
  name: "Dezo Systems & Applied Intelligence Pvt Ltd",
  legalName: "DEZO SYSTEMS AND APPLIED INTELLIGENCE PRIVATE LIMITED",
  registrationNumber: "U72900OR2021PTC037182",
  incorporationDate: "14 July 2021",
  website: "https://dezo.in",
  domain: "dezo.in",
  industry: "Enterprise AI Engineering & Digital Forensic Platforms",
  headquarters: "Bhubaneswar, Khordha, Odisha, India",
  publicLeadership: [
    {
      name: "Tarik Islam",
      role: "Founder & Chief Executive Officer",
      confidence: 99,
      source: "Ministry of Corporate Affairs (MCA21) Filing",
    },
    {
      name: "Rahul Kumar",
      role: "Director & Principal Systems Architect",
      confidence: 98,
      source: "Statutory Shareholding Disclosure & DIN Record",
    },
  ],
  publicDocuments: [
    {
      title: "Certificate of Incorporation (ROC Cuttack)",
      type: "Statutory Certificate",
      date: "2021-07-14",
      url: "https://mca.gov.in",
    },
    {
      title: "Startup Odisha Recognition OD-MSME-2022-8192",
      type: "State Grant & Industry Accreditation",
      date: "2022-09-18",
      url: "https://startupodisha.gov.in",
    },
    {
      title: "Zero Trust & Forensic RAG Architecture Whitepaper",
      type: "Technical Specification",
      date: "2025-04-10",
      url: "https://dezo.in/research",
    },
  ],
  products: [
    "Autonomous Agent Orchestration Engine",
    "ForensicKit (Aegis-DF Memory Triage)",
    "Indic Guard Multilingual Threat Classifier",
    "High-Assurance Enterprise Web Platforms",
  ],
  publicLocations: [
    "Bhubaneswar, Odisha (Registered HQ)",
    "Bengaluru, Karnataka (Engineering Node)",
  ],
  newsHighlights: [
    {
      title: "Dezo Systems Selected Among Top Deep-Tech Innovators at Eastern AI Summit",
      publisher: "Tech Herald Odisha",
      date: "March 2024",
      url: "https://odishabytes.com",
    },
    {
      title: "Engineering Sovereign AI: How Indian Startups Build Evidence-First Pipelines",
      publisher: "National Cyber Review",
      date: "January 2026",
      url: "https://dezo.in/news",
    },
  ],
  relationships: [
    {
      entity: "NIT Rourkela Alumni Innovation Enclave",
      type: "Academic Research Partner",
      evidence: "Joint research publication in IEEE CloudCom",
    },
    {
      entity: "Startup Odisha MSME Mission",
      type: "Government Industrial Accreditation",
      evidence: "Gazette Notification No. MSME-OD-8192",
    },
  ],
};

export const DEMO_WEBSITE: import("@/lib/find-someone/types").WebsiteIntelligence = {
  domain: "dezo.in",
  title: "Dezo.in — Applied AI & Forensic Software Studio",
  description:
    "Multidisciplinary technology company engineering intelligent software, autonomous AI agent platforms, and digital forensic systems.",
  organizationContext: "Dezo Systems & Applied Intelligence Pvt Ltd (CIN U72900OR2021PTC037182)",
  technologyProfile: [
    {
      category: "Frontend & UI Architecture",
      technologies: ["React 19", "TypeScript 5.8", "Tailwind CSS v4", "Vite 8", "Three.js r185"],
    },
    {
      category: "Edge & Server Infrastructure",
      technologies: ["Cloudflare Anycast Edge", "Nitro Engine", "Vercel Enterprise Edge CDN"],
    },
    {
      category: "Security & Standards",
      technologies: [
        "Strict Content-Security-Policy",
        "HSTS Preloaded",
        "Zero External CDNs",
        "TLS 1.3",
      ],
    },
  ],
  publicPages: [
    { path: "/", title: "Main Studio Dossier", status: 200 },
    { path: "/research", title: "Applied Research & Whitepapers", status: 200 },
    { path: "/security", title: "Responsible Disclosure & Security Guidelines", status: 200 },
    { path: "/privacy", title: "Public Information & Privacy Statement", status: 200 },
  ],
  publicDocuments: [
    {
      title: "Public PGP Encryption Keyring",
      type: "Cryptographic Key",
      url: "https://dezo.in/.well-known/security.txt",
    },
    {
      title: "Sovereign AI Security Architecture v2",
      type: "PDF Specification",
      url: "https://dezo.in/research/sovereign-ai.pdf",
    },
  ],
  publicOutboundLinks: [
    "https://github.com/tarikk786786",
    "https://data.gov.in",
    "https://nitrkl.ac.in",
  ],
  relatedDomains: ["dezo.dev", "tarikislam.in"],
  newsMentions: 14,
  securityObservations: [
    {
      title: "Strict Transport Security (HSTS)",
      status: "healthy",
      detail: "Configured with max-age=63072000, includeSubDomains, and preload flags verified.",
    },
    {
      title: "Defensive CSP & Anti-Tampering",
      status: "healthy",
      detail:
        "No untrusted third-party trackers or ad-network scripts detected across public assets.",
    },
    {
      title: "Standardized RFC 9116 security.txt",
      status: "healthy",
      detail: "Present at /.well-known/security.txt with active contact and PGP key fingerprint.",
    },
  ],
};

export const DEMO_DOCUMENT: import("@/lib/find-someone/types").DocumentIntelligence = {
  title: "Volatile Memory Triage in Multi-Tenant Cloud Architectures",
  documentType: "Scientific Technical Paper (PDF)",
  fileSize: "2.4 MB",
  pageCount: 14,
  authorContext: "Rahul Kumar, Department of Computer Science & Engineering, NIT Rourkela",
  detectedLanguage: "English (EN) with Indic transliteration references",
  extractedEntities: [
    { type: "Algorithm", name: "SHA-256 Merkle Evidence Tree", frequency: 28 },
    { type: "Architecture", name: "Zero Trust Triage", frequency: 19 },
    { type: "Jurisdiction", name: "ISO/IEC 27037 Standard", frequency: 14 },
    { type: "Organization", name: "NIT Rourkela", frequency: 9 },
  ],
  organizationsMentioned: [
    "National Institute of Technology Rourkela",
    "IEEE Computer Society",
    "Dezo Systems Research Enclave",
  ],
  importantDates: [
    "2019-11-14 (Original Presentation Date)",
    "2021-03-02 (Archival Acceptance)",
    "2025-06-18 (Peer Replication Benchmark)",
  ],
  keyFindings: [
    "Volatile memory acquisition can be cryptographically verified without halting host hypervisors.",
    "Deterministic page hashing reduces forensic capture false-positives by 84% compared to legacy dumps.",
    "Complies with digital forensic chain-of-custody requirements under Section 65B of the Indian Evidence Act.",
  ],
  referencedSources: [
    "IEEE Xplore Digital Archive (DOI 10.1109/CLOUDCOM.2019.00042)",
    "NIST Special Publication 800-86 Guide to Integrating Forensic Techniques",
    "ISO/IEC 27037 Digital Evidence Identification & Collection Principles",
  ],
  timelineExcerpts: [
    { date: "2018-05", event: "Undergraduate prototype implemented in C and Rust" },
    { date: "2019-11", event: "Peer-reviewed presentation at CloudCom" },
    { date: "2021-07", event: "Production integration into Dezo Systems triage pipeline" },
  ],
};

export const DEMO_IMAGE: import("@/lib/find-someone/types").ImageIntelligence = {
  fileName: "evidentiary_lab_capture_2026.jpg",
  fileSize: "4.8 MB",
  dimensions: "4032 × 3024 pixels (12.2 MP)",
  cameraExif: {
    make: "Apple",
    model: "iPhone 16 Pro",
    software: "iOS 19.4.1",
    captureTime: "2026-05-10 14:18:49 IST",
    gpsCoordinates: "12.9706° N, 77.5923° E (Coarse metropolitan region: Bengaluru)",
  },
  visibleTextExtracted: [
    "DEZO SYSTEMS — CYBER FORENSICS UNIT",
    "STATION-04 // MEMORY ACQUISITION IN PROGRESS",
    "HASH: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "ISO/IEC 27037 AUDIT CHAIN VERIFIED",
  ],
  identifiedDocumentElements: [
    "Hardware write-blocker diagnostic LCD display",
    "Multi-monitor command interface with memory graphs",
    "Official laboratory chain-of-custody seal badge",
  ],
  contextualClues: [
    "Workstation display aligns with Dezo Systems forensic terminal UI",
    "Technical lighting and equipment consistent with dedicated hardware forensics suite",
    "Zero residential or sensitive private personal indicators detected",
  ],
  potentialSourceContext:
    "Photographic artifact published in Dezo Systems technical capabilities showcase and annual research dossier.",
  attributionCaveat:
    "Forensic Principle: Optical and metadata artifacts provide corroborating context but never constitute absolute legal identity attribution without corroborating cryptographic hashes.",
};

export const INTENT_OPTIONS = [
  {
    id: "person",
    label: "Find Someone",
    description: "Search a public person, researcher, or professional identity",
    placeholder: "Enter a person's name or public handle...",
    sample: "Rahul Kumar Odisha",
  },
  {
    id: "company",
    label: "Find a Company",
    description: "Research a registered business, startup, or organization",
    placeholder: "Enter a company name or registration number...",
    sample: "Dezo Systems Pvt Ltd",
  },
  {
    id: "website",
    label: "Investigate a Website",
    description: "Understand a public domain, technology profile, and ownership",
    placeholder: "Enter a website domain (e.g. example.com)...",
    sample: "dezo.in",
  },
  {
    id: "evidence",
    label: "Search Evidence",
    description: "Find public documents, research papers, and gazette records",
    placeholder: "Enter an evidence query, topic, or document title...",
    sample: "Memory Forensics Whitepaper",
  },
  {
    id: "connections",
    label: "Explore Connections",
    description: "Discover relationships between people, companies, and institutions",
    placeholder: "Enter entity names to map connections...",
    sample: "Rahul Kumar Dezo Systems",
  },
  {
    id: "document",
    label: "Analyze a Document",
    description: "Upload and analyze a PDF document, extract entities and timeline",
    placeholder: "Drop or select a public document to inspect...",
    sample: "Volatile Memory Triage Whitepaper.pdf",
  },
  {
    id: "image",
    label: "Analyze an Image",
    description: "Inspect metadata, visible text, and public visual clues",
    placeholder: "Drop or select an image to inspect metadata and text...",
    sample: "evidentiary_lab_capture_2026.jpg",
  },
] as const;

export const SAMPLE_QUERIES = [
  { label: "Rahul Kumar (Odisha)", query: "Rahul Kumar Odisha", type: "person" },
  { label: "Dezo Systems Pvt Ltd", query: "Dezo Systems Pvt Ltd", type: "company" },
  { label: "dezo.in (Domain)", query: "dezo.in", type: "website" },
  { label: "Tarik Islam (Founder)", query: "Tarik Islam Dezo", type: "person" },
  { label: "@rahul_sec (Username)", query: "@rahul_sec", type: "person" },
  { label: "Memory Forensics Paper", query: "Volatile Memory Triage Whitepaper", type: "document" },
];
