/**
 * Modular Intelligence Platform — Module Registry (PRD §1, §2, §31, §37)
 *
 * Implements the 5-layer platform architecture:
 * PORTFOLIO UI ↓ APPLICATION / API ↓ ORCHESTRATION ENGINE ↓ TOOL + MODULE ECOSYSTEM ↓ DATA / EVIDENCE / KNOWLEDGE LAYER
 *
 * Every major capability is a decoupled module with its own manifest, feature flags,
 * inputs, outputs, risk levels, and health status.
 */

export type ModuleCategory =
  | "intelligence"
  | "research"
  | "safety"
  | "core"
  | "platform"
  | "admin";

export type ModuleStatus =
  | "enabled"
  | "disabled"
  | "beta"
  | "experimental"
  | "deprecated";

export type ModuleRiskLevel =
  | "low"
  | "medium"
  | "high"
  | "medical-safety"
  | "restricted-osint";

export interface ModuleManifest {
  id: string;
  code: string;
  name: string;
  shortDescription: string;
  description: string;
  category: ModuleCategory;
  version: string;
  status: ModuleStatus;
  enabled: boolean;
  route?: string;
  inputs: string[];
  outputs: string[];
  riskLevel: ModuleRiskLevel;
  permissions: string[];
  dependencies: string[];
  authoritativeSources: string[];
  lastAudited: string;
}

export const MODULE_REGISTRY: ModuleManifest[] = [
  {
    id: "person-intelligence",
    code: "01",
    name: "Person Intelligence",
    shortDescription: "Public persona, alias & biographical OSINT discovery",
    description: "Multivariate identity correlation using public developer profiles, academic citations, and biographical directories.",
    category: "intelligence",
    version: "2.1.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["full-name", "alias", "initials"],
    outputs: ["candidate-dossier", "public-profiles", "affiliations", "timeline"],
    riskLevel: "medium",
    permissions: ["public-web-reading"],
    dependencies: ["github-api", "openalex", "wikipedia", "orcid"],
    authoritativeSources: ["GitHub", "OpenAlex", "ORCID", "Wikidata"],
    lastAudited: "2026-10-06",
  },
  {
    id: "phone-intelligence",
    code: "02",
    name: "Phone Intelligence",
    shortDescription: "India & Global National Numbering Plan & Circle Engine",
    description: "TRAI / DoT 22 telecom circle allocation, E.164 parsing, STD codes, MNP evidentiary limitation analysis, and public web dorks.",
    category: "intelligence",
    version: "2.0.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["phone-number", "e164", "std-number"],
    outputs: ["number-validity", "circle-allocation", "original-operator", "timezone", "public-dorks"],
    riskLevel: "medium",
    permissions: ["numbering-metadata"],
    dependencies: ["india-phone-engine"],
    authoritativeSources: ["DoT National Numbering Plan", "TRAI LSA Directory", "ITU-T E.164"],
    lastAudited: "2026-10-06",
  },
  {
    id: "domain-intelligence",
    code: "03",
    name: "Domain Intelligence",
    shortDescription: "DNS DoH, RDAP, and Certificate Transparency telemetry",
    description: "Authoritative recursive DNS lookups, RDAP registrant metadata, and crt.sh CT-log passive subdomain discovery.",
    category: "intelligence",
    version: "2.0.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["domain-name", "fqdn"],
    outputs: ["dns-records", "rdap-registration", "ct-subdomains", "mail-exchangers"],
    riskLevel: "low",
    permissions: ["public-dns-query"],
    dependencies: ["cloudflare-doh", "rdap-org", "crt-sh"],
    authoritativeSources: ["Cloudflare DoH", "RDAP.org", "Sectigo crt.sh"],
    lastAudited: "2026-10-06",
  },
  {
    id: "email-intelligence",
    code: "04",
    name: "Email Intelligence",
    shortDescription: "Email domain infrastructure & public presence hints",
    description: "Validates MX/SPF mail hosts, RFC syntax, and extracts associated usernames without accessing inboxes.",
    category: "intelligence",
    version: "1.5.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["email-address"],
    outputs: ["mail-server-validity", "host-rdap", "username-pivot"],
    riskLevel: "medium",
    permissions: ["public-dns-query"],
    dependencies: ["cloudflare-doh", "rdap-org"],
    authoritativeSources: ["RFC 5322", "Authoritative MX DNS"],
    lastAudited: "2026-10-06",
  },
  {
    id: "username-intelligence",
    code: "05",
    name: "Username Intelligence",
    shortDescription: "Cross-platform developer & social handle verification",
    description: "Queries public developer and discussion API endpoints (GitHub, Reddit) for verified accounts.",
    category: "intelligence",
    version: "2.0.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["username", "handle"],
    outputs: ["verified-profiles", "public-repositories", "account-genesis"],
    riskLevel: "medium",
    permissions: ["public-api-reading"],
    dependencies: ["github-api", "reddit-public"],
    authoritativeSources: ["GitHub REST API", "Reddit JSON API"],
    lastAudited: "2026-10-06",
  },
  {
    id: "website-intelligence",
    code: "06",
    name: "Website Intelligence",
    shortDescription: "Technology detection, public contact & metadata parsing",
    description: "Evaluates public HTTP endpoints for security headers, technologies, and structured metadata.",
    category: "intelligence",
    version: "1.2.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["url", "domain"],
    outputs: ["technology-stack", "security-headers", "public-contacts"],
    riskLevel: "low",
    permissions: ["public-web-reading"],
    dependencies: ["cloudflare-doh"],
    authoritativeSources: ["W3C Standards", "HTTP Headers"],
    lastAudited: "2026-10-06",
  },
  {
    id: "public-records",
    code: "07",
    name: "Public Records Research",
    shortDescription: "Statutory registry and corporate filing guidance",
    description: "Formulates lawful public queries for Indian MCA, ZaubaCorp, and government gazettes.",
    category: "research",
    version: "1.1.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["company-name", "director-din", "cin"],
    outputs: ["search-dorks", "portal-links", "filing-guidance"],
    riskLevel: "low",
    permissions: ["public-web-reading"],
    dependencies: ["india-phone-engine"],
    authoritativeSources: ["Ministry of Corporate Affairs (MCA)", "Official Gazettes"],
    lastAudited: "2026-10-06",
  },
  {
    id: "document-intelligence",
    code: "08",
    name: "Document Intelligence",
    shortDescription: "Forensic document text & metadata extraction",
    description: "Performs client-side cryptographic hashing (SHA-256) and text inspection on uploaded documents.",
    category: "research",
    version: "1.8.0",
    status: "enabled",
    enabled: true,
    route: "/forensic-lab",
    inputs: ["file-upload", "document-text"],
    outputs: ["hash-digest", "character-entropy", "keyword-frequencies"],
    riskLevel: "low",
    permissions: ["local-file-reading"],
    dependencies: ["integrity-hash", "document-text"],
    authoritativeSources: ["NIST FIPS 180-4 SHA-256"],
    lastAudited: "2026-10-06",
  },
  {
    id: "image-intelligence",
    code: "09",
    name: "Image Intelligence",
    shortDescription: "EXIF metadata analysis & visual hazard symbol inspection",
    description: "Inspects image containers for header metadata, GHS warning symbols, and chemical labels.",
    category: "research",
    version: "1.0.0",
    status: "beta",
    enabled: true,
    route: "/forensic-lab",
    inputs: ["image-file"],
    outputs: ["exif-metadata", "label-classification", "camera-telemetry"],
    riskLevel: "low",
    permissions: ["local-file-reading"],
    dependencies: [],
    authoritativeSources: ["EXIF 2.32 Standard"],
    lastAudited: "2026-10-06",
  },
  {
    id: "news-intelligence",
    code: "10",
    name: "News Intelligence",
    shortDescription: "Live public RSS & curated security news feed",
    description: "Aggregates verified cybersecurity and forensic research developments across public news feeds.",
    category: "research",
    version: "1.3.0",
    status: "enabled",
    enabled: true,
    route: "/news",
    inputs: ["topic", "keyword"],
    outputs: ["news-feed", "source-attribution", "timestamps"],
    riskLevel: "low",
    permissions: ["public-web-reading"],
    dependencies: [],
    authoritativeSources: ["Curated Threat Feeds", "Press Releases"],
    lastAudited: "2026-10-06",
  },
  {
    id: "research-intelligence",
    code: "11",
    name: "Research/Paper Intelligence",
    shortDescription: "Open-access scientific publications & citations",
    description: "Queries Crossref, OpenAlex, Semantic Scholar, and PubMed for peer-reviewed papers and author citations.",
    category: "research",
    version: "2.0.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["author-name", "doi", "keyword"],
    outputs: ["paper-citations", "h-index", "open-access-dois"],
    riskLevel: "low",
    permissions: ["public-api-reading"],
    dependencies: ["crossref", "openalex", "semantic-scholar"],
    authoritativeSources: ["Crossref", "OpenAlex", "Semantic Scholar"],
    lastAudited: "2026-10-06",
  },
  {
    id: "company-intelligence",
    code: "12",
    name: "Company Intelligence",
    shortDescription: "Enterprise corporate hierarchy & digital infrastructure",
    description: "Correlates domain assets, corporate registrations, and developer organization memberships.",
    category: "intelligence",
    version: "1.4.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["company-name", "domain"],
    outputs: ["associated-domains", "corporate-filings", "developer-teams"],
    riskLevel: "low",
    permissions: ["public-web-reading"],
    dependencies: ["github-api", "rdap-org"],
    authoritativeSources: ["GitHub Orgs", "RDAP", "Company Directories"],
    lastAudited: "2026-10-06",
  },
  {
    id: "cyber-asset-intelligence",
    code: "13",
    name: "Cyber Asset Intelligence",
    shortDescription: "DFIR Toolbox & open security artifact catalog",
    description: "15 specialized DFIR open-source tools with pipeline alignment, ISO 27037 compliance, and usage tiers.",
    category: "intelligence",
    version: "2.2.0",
    status: "enabled",
    enabled: true,
    route: "/forensic-lab",
    inputs: ["incident-type", "evidence-category"],
    outputs: ["tool-pipeline", "evidentiary-compliance", "official-repositories"],
    riskLevel: "low",
    permissions: ["none"],
    dependencies: ["dfir-toolbox"],
    authoritativeSources: ["ISO/IEC 27037", "NIST SP 800-86", "RFC 3227"],
    lastAudited: "2026-10-06",
  },
  {
    id: "historical-web",
    code: "14",
    name: "Historical Web Intelligence",
    shortDescription: "Internet Archive Wayback Machine historical captures",
    description: "Queries Wayback CDX API for temporal snapshots and historical URL evolutions.",
    category: "intelligence",
    version: "2.0.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["domain", "url"],
    outputs: ["timestamped-snapshots", "archive-urls", "http-codes"],
    riskLevel: "low",
    permissions: ["public-api-reading"],
    dependencies: ["wayback-cdx"],
    authoritativeSources: ["Internet Archive Wayback Machine"],
    lastAudited: "2026-10-06",
  },
  {
    id: "toxicology-safety",
    code: "15",
    name: "Chemical Safety / Toxicology",
    shortDescription: "Poison safety reference, GHS hazards, antidotes & SDS",
    description: "Safety-focused clinical toxicology reference with AIIMS NPIC integration, PubChem hazard data, household DO-NOT-MIX matrix, and toxidrome engine. ZERO poison manufacturing or weaponization instructions.",
    category: "safety",
    version: "2.5.0",
    status: "enabled",
    enabled: true,
    route: "/toxicity",
    inputs: ["chemical-name", "cas-number", "product-type", "symptoms"],
    outputs: ["ghs-hazards", "symptoms", "first-aid-principles", "antidote-reference", "emergency-helpline"],
    riskLevel: "medical-safety",
    permissions: ["public-health-data"],
    dependencies: ["pubchem-api", "india-poison-centres"],
    authoritativeSources: [
      "AIIMS National Poisons Information Centre (NPIC)",
      "National Centre for Disease Control (NCDC)",
      "NIH PubChem",
      "WHO International Programme on Chemical Safety",
      "CDC / NIOSH Pocket Guide"
    ],
    lastAudited: "2026-10-06",
  },
  {
    id: "emergency-safety",
    code: "16",
    name: "Emergency Safety Information",
    shortDescription: "Immediate triage protocol & 24/7 Indian helpline directory",
    description: "24/7 emergency poison helpline directory (AIIMS NPIC 1800-116-117) and step-by-step non-medical triage assistance.",
    category: "safety",
    version: "2.0.0",
    status: "enabled",
    enabled: true,
    route: "/toxicity",
    inputs: ["emergency-alert", "ingestion-scenario"],
    outputs: ["immediate-helplines", "first-aid-action-steps", "centre-directory"],
    riskLevel: "medical-safety",
    permissions: ["none"],
    dependencies: ["india-poison-centres"],
    authoritativeSources: ["AIIMS NPIC New Delhi", "Emergency Response 112 / 108"],
    lastAudited: "2026-10-06",
  },
  {
    id: "knowledge-graph",
    code: "17",
    name: "Knowledge Graph",
    shortDescription: "Personal and investigation entity-relationship network",
    description: "Verified node-edge graph capturing verified academic credentials, certifications, projects, and entities.",
    category: "core",
    version: "1.5.0",
    status: "enabled",
    enabled: true,
    route: "/forensic-lab",
    inputs: ["entity-query"],
    outputs: ["nodes", "edges", "relationship-provenance"],
    riskLevel: "low",
    permissions: ["none"],
    dependencies: ["personal-knowledge-graph"],
    authoritativeSources: ["Verified Academic & Certification Registry"],
    lastAudited: "2026-10-06",
  },
  {
    id: "timeline-engine",
    code: "18",
    name: "Timeline Engine",
    shortDescription: "Chronological event extraction & temporal sequencing",
    description: "Extracts ISO timestamps and date markers from multi-source evidence to build validated historical timelines.",
    category: "core",
    version: "1.8.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["evidence-array"],
    outputs: ["chronological-events", "first-observed", "last-observed"],
    riskLevel: "low",
    permissions: ["none"],
    dependencies: ["person-engine"],
    authoritativeSources: ["Extracted Evidence Provenance"],
    lastAudited: "2026-10-06",
  },
  {
    id: "ai-researcher",
    code: "19",
    name: "AI Researcher",
    shortDescription: "Evidence-grounded conversational analyst (Ask Tarik AI)",
    description: "Zero-hallucination interactive AI assistant constrained strictly to verified portfolio & case evidence.",
    category: "core",
    version: "2.3.0",
    status: "enabled",
    enabled: true,
    route: "/",
    inputs: ["natural-language-query"],
    outputs: ["evidence-answer", "citations", "uncertainty-assessment"],
    riskLevel: "low",
    permissions: ["knowledge-base"],
    dependencies: ["ask-tarik-ai"],
    authoritativeSources: ["Tarik Islam Verified Profile", "CASE 0001 Dataset"],
    lastAudited: "2026-10-06",
  },
  {
    id: "report-generator",
    code: "20",
    name: "Report Generator",
    shortDescription: "ISO/IEC 27037 compliant investigation dossier exporter",
    description: "Generates tamper-evident Markdown & structured JSON dossiers with custody audit trails and quality tiers.",
    category: "core",
    version: "2.1.0",
    status: "enabled",
    enabled: true,
    route: "/find-someone",
    inputs: ["investigation-state"],
    outputs: ["markdown-dossier", "json-export"],
    riskLevel: "low",
    permissions: ["client-download"],
    dependencies: ["report-generator-component"],
    authoritativeSources: ["ISO/IEC 27037 Custody Principles"],
    lastAudited: "2026-10-06",
  },
  {
    id: "monitoring",
    code: "21",
    name: "Monitoring & Observability",
    shortDescription: "System health check & collector latency telemetry",
    description: "Real-time health status tracking across external collectors, DoH endpoints, and worker nodes.",
    category: "platform",
    version: "1.2.0",
    status: "enabled",
    enabled: true,
    route: "/security",
    inputs: [],
    outputs: ["health-telemetry", "component-latencies", "active-workers"],
    riskLevel: "low",
    permissions: ["none"],
    dependencies: ["capability-registry"],
    authoritativeSources: ["Internal Telemetry"],
    lastAudited: "2026-10-06",
  },
  {
    id: "notification",
    code: "22",
    name: "Notification Engine",
    shortDescription: "Audio feedback & interactive system sound telemetry",
    description: "Synthesized audio feedback (clicks, sweeps, success, error) powered by the Web Audio API.",
    category: "platform",
    version: "2.0.0",
    status: "enabled",
    enabled: true,
    route: "/",
    inputs: ["sound-event"],
    outputs: ["audio-playback"],
    riskLevel: "low",
    permissions: ["web-audio"],
    dependencies: ["sound-engine"],
    authoritativeSources: ["Web Audio API"],
    lastAudited: "2026-10-06",
  },
  {
    id: "tool-marketplace",
    code: "23",
    name: "Tool & Capability Registry",
    shortDescription: "Extensible registry of internal & external intelligence tools",
    description: "Centralized configuration layer allowing additions of tools, licensing, and timeout rules without codebase refactoring.",
    category: "platform",
    version: "2.0.0",
    status: "enabled",
    enabled: true,
    route: "/forensic-lab",
    inputs: [],
    outputs: ["tool-inventory", "license-compliance"],
    riskLevel: "low",
    permissions: ["none"],
    dependencies: ["osint-tool-registry", "dfir-toolbox"],
    authoritativeSources: ["Open Source Initiative (OSI)", "SPDX Licenses"],
    lastAudited: "2026-10-06",
  },
  {
    id: "api-platform",
    code: "24",
    name: "API Platform",
    shortDescription: "REST & RPC endpoints for modular intelligence consumption",
    description: "Unified `/api/intelligence` endpoint serving public DNS, RDAP, Person OSINT, and World OS dimensions.",
    category: "platform",
    version: "2.0.0",
    status: "enabled",
    enabled: true,
    route: "/api/intelligence",
    inputs: ["post-body-query"],
    outputs: ["json-intelligence-payload"],
    riskLevel: "low",
    permissions: ["api-access"],
    dependencies: ["nitro-runtime"],
    authoritativeSources: ["Cloudflare Worker Runtime"],
    lastAudited: "2026-10-06",
  },
  {
    id: "administration",
    code: "25",
    name: "Administration & Feature Flags",
    shortDescription: "Runtime module toggling and privacy control center",
    description: "Allows visitors and administrators to toggle telemetry, local storage retention, and inspect feature flags.",
    category: "admin",
    version: "1.4.0",
    status: "enabled",
    enabled: true,
    route: "/privacy-controls",
    inputs: ["consent-preferences"],
    outputs: ["stored-settings", "audit-trail"],
    riskLevel: "low",
    permissions: ["local-storage"],
    dependencies: [],
    authoritativeSources: ["GDPR / DPDP Act 2023 Principles"],
    lastAudited: "2026-10-06",
  },
];

// ── Registry Helpers ──────────────────────────────────────────────────────────

export function getActiveModules(): ModuleManifest[] {
  return MODULE_REGISTRY.filter((m) => m.enabled);
}

export function getModulesByCategory(category: ModuleCategory): ModuleManifest[] {
  return MODULE_REGISTRY.filter((m) => m.category === category && m.enabled);
}

export function getModuleById(id: string): ModuleManifest | undefined {
  return MODULE_REGISTRY.find((m) => m.id === id);
}

export function getPlatformModuleStats() {
  const total = MODULE_REGISTRY.length;
  const enabled = MODULE_REGISTRY.filter((m) => m.enabled).length;
  const byCategory: Record<string, number> = {};
  for (const m of MODULE_REGISTRY) {
    byCategory[m.category] = (byCategory[m.category] || 0) + 1;
  }
  return { total, enabled, byCategory };
}
