import { useState } from "react";
import { Download, FileCode, FileText, Check, ShieldCheck, Copy } from "lucide-react";
import type { Investigation } from "@/lib/find-someone/types";

interface ReportGeneratorProps {
  investigation: Investigation;
}

export function ReportGenerator({ investigation }: ReportGeneratorProps) {
  const [copied, setCopied] = useState(false);
  const [downloadFormat, setDownloadFormat] = useState<"markdown" | "json">("markdown");

  const generateMarkdown = () => {
    const p = investigation.persons[0];
    return `# PUBLIC OSINT INTELLIGENCE REPORT: ${p.name}
Generated by TarikIslam.in Find Someone Engine (v2.6)
Timestamp: ${investigation.completedAt || new Date().toISOString()}
Target Query: "${investigation.query.raw}"
Audit Standard: ISO/IEC 27037 & NIST SP 800-86
Attribution Confidence: ${p.confidence}% (${p.status.toUpperCase()})

---

## 1. EXECUTIVE SUMMARY
- **Primary Identified Subject**: ${p.name}
- **Corroborating Sources**: ${investigation.sources.length} statutory, peer-reviewed, and public directory sources
- **Entity Correlation**: ${p.metadata.designation || "N/A"}
- **Institutional Alignment**: ${p.metadata.almaMater || "N/A"}
- **Geographic Roots**: ${p.locations?.join(", ") || "N/A"}

---

## 2. DISCOVERED PUBLIC PROFILES
${p.publicProfiles.map((prof) => `- **${prof.platform}**: [${prof.username}](${prof.url}) (Confidence: ${prof.confidence}%)`).join("\n")}

---

## 3. CORPORATE & ORGANIZATIONAL MAPPINGS
${investigation.organizations.map((org) => `- **${org.name}** (${org.metadata.incorporationNumber || "Entity"}): ${org.metadata.industry || "Organization"} | Status: ${org.status}`).join("\n")}

---

## 4. CHRONOLOGICAL TIMELINE OF PUBLIC EVIDENCE
${investigation.timeline.map((evt) => `- **${evt.date}** [${evt.type.toUpperCase()}]: ${evt.title} — ${evt.description} (Source: ${evt.sourceId})`).join("\n")}

---

## 5. CONFLICT ANALYSIS & DISCREPANCY DISCLOSURE
${investigation.conflicts
  .map(
    (c) => `### ${c.field}
- Perspective A: ${c.claimA.object} ("${c.claimA.evidenceText}")
- Perspective B: ${c.claimB.object} ("${c.claimB.evidenceText}")
- Disclosure Note: ${c.description}
`,
  )
  .join("\n")}

---

## 6. STATUTORY & OPEN REGISTRY CITATIONS
${investigation.sources.map((s) => `- [${s.qualityScore}/5 ★] **${s.name}** (${s.domain}): ${s.url} (Retrieved: ${s.retrievedAt})`).join("\n")}

---
*Disclaimer: All intelligence synthesized strictly from lawful, public, un-authenticated open-source registries.*
`;
  };

  const handleCopy = () => {
    const text =
      downloadFormat === "markdown" ? generateMarkdown() : JSON.stringify(investigation, null, 2);
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content =
      downloadFormat === "markdown" ? generateMarkdown() : JSON.stringify(investigation, null, 2);
    const blob = new Blob([content], {
      type: downloadFormat === "markdown" ? "text/markdown" : "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `find_someone_report_${investigation.query.entityType}_${Date.now()}.${downloadFormat === "markdown" ? "md" : "json"}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="rounded-xl border border-white/10 bg-white/[0.025] p-5 backdrop-blur-xl space-y-4 font-mono text-xs">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-white/5">
        <div>
          <span className="text-[10px] uppercase text-[#62E6FF] tracking-wider font-bold block">
            COURT & AUDIT-GRADE REPORTING
          </span>
          <h4 className="font-display text-base font-bold text-foreground">
            Generate Evidentiary Intelligence Dossier
          </h4>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setDownloadFormat("markdown")}
            className={`px-2.5 py-1 rounded text-[11px] cursor-pointer ${
              downloadFormat === "markdown"
                ? "bg-[#62E6FF]/20 text-[#62E6FF] border border-[#62E6FF]/40 font-bold"
                : "border border-white/10 text-muted-foreground"
            }`}
          >
            Markdown (.md)
          </button>
          <button
            type="button"
            onClick={() => setDownloadFormat("json")}
            className={`px-2.5 py-1 rounded text-[11px] cursor-pointer ${
              downloadFormat === "json"
                ? "bg-[#62E6FF]/20 text-[#62E6FF] border border-[#62E6FF]/40 font-bold"
                : "border border-white/10 text-muted-foreground"
            }`}
          >
            JSON Raw Schema
          </button>
        </div>
      </div>

      <div className="rounded-lg border border-white/10 bg-black/50 p-4 max-h-60 overflow-y-auto font-mono text-[11px] text-foreground/80 leading-relaxed whitespace-pre-wrap">
        {downloadFormat === "markdown"
          ? generateMarkdown()
          : JSON.stringify(investigation, null, 2)}
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
        <div className="flex items-center gap-2 text-[10.5px] text-muted-foreground">
          <ShieldCheck className="size-4 text-[#6EE7B7]" />
          <span>Non-speculative disclosure · ISO 27037 compliant audit metadata</span>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopy}
            className="flex items-center gap-1.5 rounded-md border border-white/15 bg-white/5 px-3 py-2 text-xs font-semibold text-foreground hover:bg-white/10 transition-all cursor-pointer"
          >
            {copied ? <Check className="size-3 text-[#6EE7B7]" /> : <Copy className="size-3" />}
            <span>{copied ? "Copied" : "Copy Content"}</span>
          </button>

          <button
            type="button"
            onClick={handleDownload}
            className="flex items-center gap-1.5 rounded-md border border-[#62E6FF]/40 bg-[#62E6FF] px-4 py-2 text-xs font-bold text-[#050608] hover:bg-[#62E6FF]/90 transition-all shadow-[0_0_16px_rgba(98,230,255,0.3)] cursor-pointer"
          >
            <Download className="size-3" />
            <span>Download Report</span>
          </button>
        </div>
      </div>
    </div>
  );
}
